// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3U-frBE-oZiS_cjJ2baUplXGftCoop-A',
    appId: '1:508483008398:web:1e7249e1fa27df964916df',
    messagingSenderId: '508483008398',
    projectId: 'gift-present-app',
    authDomain: 'gift-present-app.firebaseapp.com',
    storageBucket: 'gift-present-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmpGeSh152TpjdYSkreHq3r7SOjHRW0I4',
    appId: '1:508483008398:android:7e0cb58217be071f4916df',
    messagingSenderId: '508483008398',
    projectId: 'gift-present-app',
    storageBucket: 'gift-present-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNBKNGcFJ9hG7XPL4Hls9O-HkASrnsDJ4',
    appId: '1:508483008398:ios:ca2c288034e32ff74916df',
    messagingSenderId: '508483008398',
    projectId: 'gift-present-app',
    storageBucket: 'gift-present-app.appspot.com',
    iosClientId: '508483008398-ipspahql06r6mc6h0sgdrcpkg1u76jt6.apps.googleusercontent.com',
    iosBundleId: 'com.gift.gift',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDNBKNGcFJ9hG7XPL4Hls9O-HkASrnsDJ4',
    appId: '1:508483008398:ios:f6769f0dd8e82d094916df',
    messagingSenderId: '508483008398',
    projectId: 'gift-present-app',
    storageBucket: 'gift-present-app.appspot.com',
    iosClientId: '508483008398-07eov31g2g3paohp3bp7r4vk5adcmhrk.apps.googleusercontent.com',
    iosBundleId: 'com.gift.gift.RunnerTests',
  );
}
